Feature/issue-224 Actualizacion del mid de terceros para la inscripcion de pregrado
udistrital/sga_mid_tercero pull request #15
Opened 2024-05-27 05:42 UTC by JaredPeralta

2024-05-27 15:06 UTC, NeFaWaltPint requested changes
Ajustar el detalle del puerto y lo del servicio http falta xray

2024-05-27 15:06 UTC, NeFaWaltPint commented on conf/app.conf
> +httpport = 8181
```suggestion
httpport = ${SGA_TERCERO_MID_HTTP_PORT}
```
Mantener como estaba

2024-05-27 15:06 UTC, NeFaWaltPint commented on helpers/tercero_helper.go
Esta bien, pero no se recomienda, ya que hay que llevar traza de las consultas con Xray.. en utils_oas ya hay servicios implementados que hace uso del xray https://github.com/udistrital/utils_oas/blob/master/requestresponse/requests.go
Si la petición requiere algo particular que no está en la funcionalidad comentarlo.

2024-05-27 15:07 UTC, NeFaWaltPint commented
> [!Warning]
> # Pero alto, hasta donde recuerdo, no se iba a usar mas SGA_terceros_mid, para eso está https://github.com/udistrital/terceros_mid

2024-06-04 13:27 UTC, brayaned approved these changes

2024-06-11 13:40 UTC, closed without merging